### ISSUE TITLE
complete sample, please?

### ISSUE THREAD

**Issue by ghost** [rainbowintheshell/pirata#1]
Hello
Can anyone show a complete example on how to use it, please?
how to make a search and how to show the results.
thanks in advance

**Comment by aranciaga** [comment]
Hi. In README.md you have an example code of the only function of this library. Please read.

**Comment by ghost** [comment]
hello and thanks for your response.
i saw the sample, but i'm a newbie and i don't know how to use the sample...
can you please put a complete example?
thanks in advance

**Comment by aranciaga** [comment]
Sure, but you should read more, in case you want to practice with my library:
```
  var pirata = require('pirata');

  pirata.search("Here, your query search", function(err, res){
    if(err) console.log(err); // in case of an error, we print it.
    console.log(res) // printing all results (raw). It is an array of objects. Search how to handle, basically to print first result you should print "res[0].name". But may exist the case that "res" is empty.
  });
```

However, I didn't try this code, but hope will help you

**Comment by ghost** [comment]
Thanks again;
But my problem is i don't know how to use this code inside the html page.
Can you put an example on how to use your code clicking a button?
thanks in advance.
